### ISSUE TITLE
Using the plugin causes build scans to fail

### ISSUE THREAD

**Issue by NikolayMetchev** [gradlex-org/java-ecosystem-capabilities#55] opened 2023-06-30 15:55 UTC
When trying to apply this plugin Gradle Enterprise 8.1.1 fails to create a build scan with the following error:

[2023-06-30T15:20:04.535Z] A build scan cannot be produced as an error occurred gathering build data.

[2023-06-30T15:20:04.535Z] Please report this problem via https://gradle.com/help/plugin and include the following via copy/paste:

[2023-06-30T15:20:04.536Z] 

[2023-06-30T15:20:04.536Z] ----------

[2023-06-30T15:20:04.536Z] Gradle version: 8.1.1

[2023-06-30T15:20:04.536Z] Plugin version: 3.13.3

[2023-06-30T15:20:04.536Z] 

[2023-06-30T15:20:04.536Z] com.gradle.scan.plugin.internal.m.a: Build operation dispatch of finished notification failed.

[2023-06-30T15:20:04.536Z] Operation context: 

[2023-06-30T15:20:04.536Z] 	org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$1 (1): {}

[2023-06-30T15:20:04.536Z] 	org.gradle.configurationcache.StoreDetails (126659): {}

[2023-06-30T15:20:04.536Z] 	org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationDetails (133213): {describe error: java.lang.IllegalAccessException: class com.gradle.scan.plugin.internal.m.a cannot access a member of class org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationDetails with modifiers "public"}

[2023-06-30T15:20:04.536Z] Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':test:e2e:swift-gateway:testRuntimeClasspath'.

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:107)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:214)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:60)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.c.i.a.e$a.b(SourceFile:115)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.c.i.a.e$a.a(SourceFile:72)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.c.i.a.e.a(SourceFile:51)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.c.i.a.d.a(SourceFile:180)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.c.i.c.a(SourceFile:140)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.m.b$c.finished(SourceFile:154)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.m.b.a(SourceFile:65)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.m.n.a(SourceFile:56)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.m.d.a(SourceFile:112)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.m.h.a(SourceFile:51)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.r.a$a.a(SourceFile:31)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.r.a$a.a(SourceFile:20)

[2023-06-30T15:20:04.536Z] 	at com.gradle.scan.plugin.internal.r.a.c(SourceFile:67)

[2023-06-30T15:20:04.536Z] Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /tmp/gradle/.tmp/gradle1952635425262414418.bin offset 8014850 exists? true

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:136)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:190)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:188)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:160)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:51)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:212)

[2023-06-30T15:20:04.536Z] 	... 14 more

[2023-06-30T15:20:04.536Z] Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (714) for runtime -> com.sun.activation:jakarta.activation:1.2.2

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:240)

[2023-06-30T15:20:04.536Z] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:134)

[2023-06-30T15:20:04.536Z] 	... 20 more

[2023-06-30T15:20:04.536Z] ----------

**Comment by NikolayMetchev** [comment] 2023-06-30 16:11
I think the problem is the plugin doesn't support configuration cache.

**Comment by jjohannes** [comment] 2023-07-01 06:48
The plugin supports the configuration cache. At lease I haven't seen any issues there yet.

The problem you are seeing is one (or several) bug(s) in Gradle related to capability resolution (most likely). It's only coincident that the build scan publish is triggering it. You may also see it during IDE import for example.

It can also be reproduced in the tests we have by reordering dependencies. See:
https://github.com/gradle/gradle/issues/14220#issuecomment-1407125074

The workarounds are to change dependency order or to directly remove something that's involved in the conflict triggering the exception through a component metadata rule. But the hard part is to find out what is causing it. 😞 

I am talking to folks at Gradle if they can prioritize fixing this.

Feel free to comment on the issues at Gradle as well. There seem to be two on the topic:
- https://github.com/gradle/gradle/issues/14220
- https://github.com/gradle/gradle/issues/14946

**Comment by jjohannes** [comment] 2024-01-04 19:04
Since there is no reproducer at the moment that shows that there is an issue with the configuration cache that can be fixed in the plugin, I am closing this issue. Please comment (or open a new issue) if there is something I am missing.

**Closed by jjohannes** 2024-01-04 19:04 UTC
Labels: question
