### ISSUE TITLE
Error when using plugin with lockfiles

### ISSUE THREAD

**Issue by MatanSabag** [gradlex-org/java-ecosystem-capabilities#51] opened 2023-06-18 11:36 UTC
When I use this plugin with lockfiles without any special configurations, when I try to `resolveAndLockAll` I get the following error:

> Execution failed for task ':tony:tony-server:resolveAndLockAll'.
> Could not resolve all files for configuration ':tony:tony-server:default'.
   > Could not resolve jakarta.xml.bind:jakarta.xml.bind-api:2.3.2.
     Required by:
         project :tony:tony-server
         project :tony:tony-server > project :tony:tony-api
      > Module 'jakarta.xml.bind:jakarta.xml.bind-api' has been rejected:
           Cannot select module with conflict on capability 'jakarta.xml.bind:jakarta.xml.bind-api:2.3.3' also provided by [jakarta.xml.bind:jakarta.xml.bind-api:2.3.2(runtime)]
   > Could not resolve javax.xml.bind:jaxb-api:2.3.1.
     Required by:
         project :tony:tony-server > org.jooq:jooq:3.14.12
         project :tony:tony-server > com.redacted:tilestorage:2.0.78.0 > org.ehcache:ehcache:3.8.0 > org.glassfish.jaxb:jaxb-runtime:2.3.1
      > Module 'jakarta.xml.bind:jakarta.xml.bind-api' has been rejected:
           Cannot select module with conflict on capability 'jakarta.xml.bind:jakarta.xml.bind-api:2.3.3' also provided by [jakarta.xml.bind:jakarta.xml.bind-api:2.3.2(runtime)]
   > Could not resolve jakarta.xml.bind:jakarta.xml.bind-api:2.3.3.
     Required by:
         project :tony:tony-server > com.redacted:redacted-server:4.2.30.0 > org.glassfish.jersey.media:jersey-media-json-jackson:2.33 > com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.15.2
      > Module 'jakarta.xml.bind:jakarta.xml.bind-api' has been rejected:
           Cannot select module with conflict on capability 'jakarta.xml.bind:jakarta.xml.bind-api:2.3.3' also provided by [jakarta.xml.bind:jakarta.xml.bind-api:2.3.2(runt

Now, if I add the following to my `build.gradle` file:

```
configurations.all {
    resolutionStrategy.capabilitiesResolution {
        withCapability("jakarta.xml.bind:jakarta.xml.bind-api") {        // Capability for which to make the decision
            select("jakarta.xml.bind:jakarta.xml.bind-api:2.3.3")    // The component to select
        }
    }
}

```

the `resolveAndLockAll` task passes. But when I run `./gradlew clean build` I get the following error:

> * What went wrong:
Could not determine the dependencies of task ':tonycoding:server:test'.
> Could not resolve all task dependencies for configuration ':tonycoding:server:testRuntimeClasspath'.
   > Did not resolve 'jakarta.activation:jakarta.activation-api:1.2.2' which is part of the dependency lock state
   > Did not resolve 'javax.xml.bind:jaxb-api:2.3.1' which is part of the dependency lock state

I use Gradle 7.6.1

**Comment by jjohannes** [comment] 2023-06-25 08:05
I assume that somehow during 'resolveAndLockAll' the classpath contains more/less information than when you do the actual building. This is probably more an "issue" with these mechanisms in Gradle than with this plugin.

Could you provide a reproducer for the problem? And/or Build Scans for the two runs?

**Comment by jjohannes** [comment] 2024-01-04 19:05
Since there is not reproduce that shows what could/should be fixed in the plugin, I am closing this issue. Please comment or open a new issue if there is anything I am missing.

**Closed by jjohannes** 2024-01-04 19:05 UTC
Labels: question
